apiVersion: v1
kind: Service
metadata:
  name: wahaj-app-service
  namespace: wahaj-app
  labels:
    app: wahaj-app
    student: fa22-bse-100
spec:
  type: NodePort
  selector:
    app: wahaj-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
